apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-main
  namespace: default
  labels:
    app.kubernetes.io/name: alertmanager
stringData:
  alertmanager.yaml: |-
    global:
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_from: '2005nguyendang@gmail.com'
      smtp_auth_username: '2005nguyendang@gmail.com'
      smtp_auth_password: 'uvxf srqy ejqz garf'  
    route:
      receiver: email-alert
      group_wait: 10s
      group_interval: 1m
      repeat_interval: 30m
    receivers:
      - name: email-alert
        email_configs:
          - to: 'danqng0911@gmail.com'
