apiVersion: v1
kind: Service
metadata:
  name: week7-cicd
  namespace: week7
  labels:
    app: week7-cicd 
spec:
  type: LoadBalancer
  selector:
    app: week7-cicd
  ports:
    - name: http
      port: 8080
      targetPort: 8080
