apiVersion: apps/v1
kind: Deployment
metadata:
  name: week7-cicd
  namespace: week7
spec:
  replicas: 3
  selector:
    matchLabels:
      app: week7-cicd
  template:
    metadata:
      labels:
        app: week7-cicd
    spec:
      containers:
        - name: week7-cicd
          image: dangnguyen091105/week7-cicd:latest   # ✅ thay bằng image thật của bạn
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/demo_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
            - name: SPRING_DATASOURCE_USERNAME
              value: demo_user
            - name: SPRING_DATASOURCE_PASSWORD
              value: "12345"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
              value: org.hibernate.dialect.MySQL8Dialect
